global using PKMDS_CS;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Drawing;
global using System.Drawing.Imaging;
global using System.IO;
global using System.Runtime.InteropServices;
global using System.Windows.Forms;
global using static PKMDS_CS.PKMDS;
